### ISSUE TITLE
Please provide a sample setup to crawl a website and store the content in Solr repo.

### ISSUE THREAD

**Issue by raviks007** [Norconex/crawlers#41]
Please provide a sample setup to crawl a website and store the content in Solr repo. Also we have other requirements like, indexing Metadata, skip certain URLs, parsing only part of a content page and also parsing the data from oracle database. 

Is it possible to give a best example to help me to implement the above requirements. We are actually looking to finalise to go with Apache Nutch or Norconex. I have no experience in Norconex as I just read about it since yesterday. It will be helpful if you can provide the inputs so that I can showcase and decide on the crawler.

Thanks,
Ravi

**Comment by liar666** [comment]
I'm re-opening it since the provided example does not work:
1. because of bug:
https://github.com/Norconex/collector-http/issues/255
2. it raises
```
com.norconex.collector.core.CollectorException: Cannot load crawler configurations.
        at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfigs(CrawlerConfigLoader.java:93)
        at com.norconex.collector.core.AbstractCollectorConfig.loadFromXML(AbstractCollectorConfig.java:183)
        at com.norconex.collector.core.CollectorConfigLoader.loadCollectorConfig(CollectorConfigLoader.java:78)
        at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:76)
        at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)
Caused by: com.norconex.commons.lang.config.ConfigurationException: This class could not be instantiated: "com.norconex.collector.http.filter.impl.RegexReferenceFilter".
        at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:190)
        at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:333)
        at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:265)
        at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:115)
        at com.norconex.collector.core.crawler.AbstractCrawlerConfig.loadReferenceFilters(AbstractCrawlerConfig.java:387)
        at com.norconex.collector.core.crawler.AbstractCrawlerConfig.loadFromXML(AbstractCrawlerConfig.java:314)
        at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfig(CrawlerConfigLoader.java:123)
        at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfigs(CrawlerConfigLoader.java:83)
        ... 4 more
Caused by: java.lang.ClassNotFoundException: com.norconex.collector.http.filter.impl.RegexURLFilter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:188)
        ... 11 more

```

**Comment by liar666** [comment]
According to minimal example, it has been move to:
com.norconex.collector.core.filter.impl.RegexReferenceFilter

:)

**Comment by shreyu2403** [comment]
hi ,
for making this xml file run what changes have to be done in collector-http.sh file.
im trying to run it but produces this error
collector-http.sh: 4: collector-http.sh: realpath: not found
log4j:ERROR Could not read configuration file from URL [file:/log4j.properties].
java.io.FileNotFoundException: /log4j.properties (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileInputStream.<init>(FileInputStream.java:101)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:557)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at com.norconex.collector.core.AbstractCollector.<clinit>(AbstractCollector.java:58)
log4j:ERROR Ignoring configuration file [file:/log4j.properties].
Invalid configuration file path: /home/iitp/Downloads/norconex-collector-http-2.7.1/document-collector.xml

please help

**Comment by essiembre** [comment]
``realpath`` is a command often present on your OS but you can install if not.   Another option is simply to replace ``export ROOT_DIR=$(realpath $(dirname $0))`` with the hardcoded path of the directory where ``collector-http.sh`` is found.  Example:

```
export ROOT_DIR=/home/iitp/Downloads/norconex-collector-http-2.7.1
```
The reason for using ``realpath`` is for situations where you invoke the script from a different directory (then relative paths may be affected).  Hard-coding the path as the same effect.
