### ISSUE TITLE
List names of failed jobs when crawl finishes

### ISSUE THREAD

**Issue by ohtwadi** [Norconex/crawlers#504]
When CRAWLER_FINISHED event happens and one (or more) jobs have resulted in an error, it notes the number of failed jobs. It would be nice to list names of these failed jobs as well.

CoC WDS HTTP Collector: 2018-07-10 22:38:23 ERROR - Execution failed for job: CoC WDS HTTP Collector
com.norconex.jef4.job.JobException: 1 out of 6 jobs failed in async group "CoC WDS HTTP Collector"
        Failed Jobs IDs: [job1, job2]  <<<==== Add something like this ====>>>
	at com.norconex.jef4.job.group.AsyncJobGroup.executeGroup(AsyncJobGroup.java:105)
	at com.norconex.jef4.job.group.AbstractJobGroup.execute(AbstractJobGroup.java:80)
	at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:355)
	at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:296)
	at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:168)
	at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:132)
	at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:95)
	at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:74)

**Comment by essiembre** [comment]
You will find what job failed earlier in the log.  I am marking it as a feature request to have it also reported as part of a status summary at the end.

**Comment by ohtwadi** [comment]
Thank you.
